### ISSUE TITLE
Alert not showed with minimalCustomizationPresentationExample() configuration

### ISSUE THREAD

**Issue by giofid** [ArtSabintsev/Siren#326] opened 2020-02-13 11:46 UTC
Hi Arthur,
thank you for this great library!

I'm trying the example in the project and I saw that the alert is not showed with `minimalCustomizationPresentationExample()` configuration. I think the problem is that `PresentationManager(alertTintColor: .purple, appName: "Siren Example App Override!")` is called before `application(_ application: didFinishLaunchingWithOptions launchOptions:)` is terminated and in the [`PresentationManager.createWindow()`](https://github.com/ArtSabintsev/Siren/blob/32de6efe8b6de45f01d24f9a29e8a15f1a2e9067/Sources/Managers/PresentationManager.swift#L230) the `UIApplication.shared.connectedScenes` array is yet empty.

**Comment by ArtSabintsev** [comment] 2020-02-13 14:47
Hey! Will look into this!

**Comment by ArtSabintsev** [comment] 2020-02-16 01:09
I am able to faithfully reproduce this issue, but the `else` close in the statement still returns an empty UIWindow, so it should still work. I'm looking into it, but I'm open to any assistance here.

**Comment by ArtSabintsev** [comment] 2020-02-16 01:18
ok, fixed the example app. With the latest change, all code should be executed in `didBecomeActive`, due to the issue you mentioned.

This doesn't require a version change, so I'll just update the sample app and pos tit here shortly before closing the issue.

**Comment by giofid** [comment] 2020-02-17 08:37
Sorry @ArtSabintsev,
but I think that this fix breaks the `.onDemand` perform check. Now the alert is showed every time the app become active, regardless of `performCheck` parameter in the `wail` method.

In my opinion, you should revert these changes: it is correct to place the siren setup in `UIApplication.didFinishLaunchingWithOptions`. The problem is that you create the `updaterWindow` (in the `PresentationManager`) at initialization time. Too soon. You need it only when you present the alert. So delay its creation.

**Comment by ArtSabintsev** [comment] 2020-02-18 14:39
would you mind putting in a PR? I'm a bit low on time at the moment. It'll give me a starting point.

**Closed** 2020-02-18 14:40 UTC
Labels: Potential Bug
