### ISSUE TITLE
Xcode warning because of bundle

### ISSUE THREAD

**Issue by Robuske** [ArtSabintsev/Siren#357] opened 2020-12-18 00:59 UTC
Xcode is showing a warning because of the _Siren.bundle_ folder.
Probably is because of the fact that SPM 5.3 supports resources, so it's complaining that the resource is not declared, but I haven't read enough about SPM resources so I am not sure how to fix.

```
found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target

/path/to/folder/Xcode/DerivedData/app-name/SourcePackages/checkouts/Siren/Sources/Siren.bundle
```

**Comment by ArtSabintsev** [comment] 2020-12-18 13:12
Thanks for the heads up. I'll look into it!

**Comment by ArtSabintsev** [comment] 2020-12-21 13:10
The issue is now addressed in #358. I'll merge it in soon.

**Comment by Robuske** [comment] 2020-12-21 13:26
Thanks 😄

**Comment by ArtSabintsev** [comment] 2020-12-21 15:30
Released as 5.7.0. Thanks again!

**Closed by ArtSabintsev** 2020-12-21 15:30 UTC
Labels: Enhancement, Potential Bug
