### ISSUE TITLE
[Siren] Error parsing App Store JSON data - Version 3.9.1

### ISSUE THREAD

**Issue by Vaifathuy** [ArtSabintsev/Siren#251] opened 2018-11-28 03:41 UTC
*****NOTE**: I have updated Siren to the latest version, which is 3.9.1
- Bundle ID: socheat.ournsarat.app
- latest version of your app published to the App Store -: 25 Oct 2018
- Is your app Published in the US App Store?: YES

**Error Message**
[Siren] Error parsing App Store JSON data.
Also, the following system level error was returned: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "trackId", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))

**Comment by ArtSabintsev** [comment] 2018-11-28 14:08
Are you sure you’re using 3.9.1?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment] 2018-11-30 02:47
I launched the sample app in this repo and replaced the bundle ID in there with yours and it worked just fine.

Feel free to share a snippet of code.

**Comment by ArtSabintsev** [comment] 2018-11-30 16:20
Closing the issue, since I cannot reproduce it. Feel free to respond and I'll follow up.

**Closed by ArtSabintsev** 2018-11-30 16:20 UTC
