### ISSUE TITLE
The app ignores `alertType = .force` if already skipped an update

### ISSUE THREAD

**Issue by mamouneyya** [ArtSabintsev/Siren#115] opened 2017-01-15 02:14 UTC
Hello,

In the app I'm currently developing, I have an API service that is called to decide the `alertType` value. The problem is that in some cases I could specify a value of `force` *after* the user has already chose to skip the update. In that case, the library prioritizes the saved skip over the force type, ending up with no popup shown, which I honestly find it wrong. I think that force alert type should override this... no?

**Comment by ArtSabintsev** [comment] 2017-01-15 06:15
Hey again,

In this case, the library is functioning as intended. 

The goal of the library is to provide the user with a good experience. Therefore, if the user sees an update for a specific version, let's call it 1.0.1, and they decide to skip that version, the library respects that decision and will _never ever_ show them an update for 1.0.1 again. 

Your case is unique because you dynamically change the `alertType`, _after_ presentation, for a specific `alertType`. I can see the merit of you doing this because you may want to force people to upgrade if they are way out of date or if a nasty bug is discovered. 

With all of that in mind, I believe that your scenario is _too_ situational. I am in the business of building and supporting software with simple interfaces that solve problems for _90%_ of common situations. Due to this philosophy, I am going to politely decline this request.

On that note, I do have a design suggestion for you. Instead of prompting users to update right away, add a flag to your server-side configuration file that defaults to false for the presentation of a Siren alert: `shouldPresentSirenAlert = false`. Afterwards, wait a week or two before changing the flag to `true`, and in the same file pass in the a value for `alertType` as well. Therefore, you give yourself enough time to get decent user adoption. This then allows you to remotely control when users' are presented with a Siren alert and the type of alert they see.

That would be my suggestion based on personal experience of doing something similar.

Closing this issue as I am against adding this into Siren, but feel free to comment back, and I will happily respond and continue the discussion.

cc @getaaron (for any input you may have)

**Closed by ArtSabintsev** 2017-01-15 06:15 UTC

**Comment by mamouneyya** [comment] 2017-01-15 10:19
Well, this makes some sense. I guess I would go with your suggestion or a somehow modified version of it..

**Comment by ArtSabintsev** [comment] 2017-01-15 15:25
Sounds good! Best of luck with the implementation!
