### ISSUE TITLE
Version 3.5.0 is not building anymore with Carthage

### ISSUE THREAD

**Issue by jdanthinne** [ArtSabintsev/Siren#225] opened 2018-09-17 08:14 UTC
Just tried to use 3.5.0 with Carthage, but project won't build… I switched to "master" to make sure to have the lasted code, but still got the same error.

`/Siren/Sources/SirenUIAlertControllerExtension.swift:18:30: error: type 'UIWindow.Level' (aka 'CGFloat') has no member 'alert'`

**Comment by ArtSabintsev** [comment] 2018-09-17 09:11
Per release notes, the latest version is using Xcode 10 and Swift 4.2.

Does that help?

There is a Swift 4/4.1 branch if you need that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdanthinne** [comment] 2018-09-17 09:13
I'm already using XCode 10 and Swift 4.2 in my project. I reverted to 3.4.3 and everything is ok.

**Comment by ArtSabintsev** [comment] 2018-09-17 11:18
Sorry about that. I'll take a look this evening. Thanks for bringing this to my attention!

**Comment by ArtSabintsev** [comment] 2018-09-18 00:03
Works for me. I ran `carthage update` and dragged the binary into the project and added it into the `embedded framework` as well and it just worked in a new project in Xcode 10.

See the attached project and screenshot.

<img width="541" alt="screen shot 2018-09-17 at 8 02 40 pm" src="https://user-images.githubusercontent.com/854860/45656646-a5013700-bab4-11e8-8ebb-70d7eb27e060.png">

[Test.zip](https://github.com/ArtSabintsev/Siren/files/2390627/Test.zip)

Keep me posted. Closing the issue for now since it's not reproducible on my end. Feel free to follow up.

**Closed by ArtSabintsev** 2018-09-18 00:03 UTC

**Comment by jdanthinne** [comment] 2018-09-18 06:29
I believe you. Unfortunately, still unable to build after cleaning Carthage cache, Derived data, etc.

**Comment by ArtSabintsev** [comment] 2018-09-18 10:48
Can you send me a sample project?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdanthinne** [comment] 2018-09-18 13:03
Unfortunately no, it's part of a very big project.
I confirm it works like a charm with a new project, so the issue must have something to do with my project config I guess.

Here's the log of carthage:
`*** Building scheme "Siren" in SirenExample.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/jdanthinne/Développement/Swift/Apps/GroomService/Carthage/Checkouts/Siren/SirenExample/SirenExample.xcodeproj -scheme Siren -configuration Release -derivedDataPath /Users/jdanthinne/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/Siren/3.5.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/vh/np47mx2j3tl752jkkjh1tyj40000gn/T/Siren SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/…/Carthage/Checkouts/Siren)`

**Comment by ArtSabintsev** [comment] 2018-09-19 01:44
Not sure what to tell you, my friend. I don't use Carthage, nor do I know why you'd be getting this error. Maybe you need to update Carthage and do a fresh install of Siren?
