### ISSUE TITLE
CFNetwork SSLHandshake failed (-9801) errors

### ISSUE THREAD

**Issue by jsoendermann** [ArtSabintsev/Siren#66] opened 2016-05-24 15:34 UTC
Hi,

when I try to use Siren in my app, I get SSL errors on startup:

```
CFNetwork SSLHandshake failed (-9801)
CFNetwork SSLHandshake failed (-9801)
CFNetwork SSLHandshake failed (-9801)
CFNetwork SSLHandshake failed (-9801)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9801)
```

Do I have to add a URL to my App Transport Security exceptions for Siren to work?

**Comment by ArtSabintsev** [comment] 2016-05-24 15:41
Hmm, I've never had to do that. What's your ATS settings look like?

**Comment by ArtSabintsev** [comment] 2016-05-24 15:42
and yes, that will probably fix the problem.

**Comment by jsoendermann** [comment] 2016-05-24 16:03
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSAllowsArbitraryLoads</key>
				<true/>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

Which Domain would I have to add to make it work?

**Comment by ArtSabintsev** [comment] 2016-05-24 16:06
Hmm, you should be fine with those settings. I'm surprised it didn't work. I'll have to get back to you on that.

**Comment by jsoendermann** [comment] 2016-05-25 12:32
Thanks!

**Comment by getaaron** [comment] 2016-05-25 12:36
I can't reproduce this. Are you using something like Charles or Wireshark?

**Comment by ArtSabintsev** [comment] 2016-05-25 15:53
Closing the issue as it's not reproducible

**Comment by ArtSabintsev** [comment] 2016-05-25 16:33
Re-opening for feedback, but there's not much we can do on our end.

**Comment by ArtSabintsev** [comment] 2016-06-02 16:46
As there's been no feedback in about a week, I'm closing this issue.

**Closed by ArtSabintsev** 2016-06-02 16:46 UTC
