### ISSUE TITLE
iTunes API returns different results

### ISSUE THREAD

**Issue by Bernica** [ArtSabintsev/Siren#252] opened 2018-12-10 19:30 UTC
Hi there!

So, I'm aware this is really an iTunes lookup API bug, but wanted you to know about it in case you want to do something.

I've just updated my live version of my app, and debugging why the update message didn't appear I got inside the library.

I also looked at the iTunes lookup API.

Well, the fact is that when asking for https://itunes.apple.com/lookup?id=[ID] the API returns the new version, while when asking for https://itunes.apple.com/lookup?bundleId=[BundleID] it returns the old version.

Siren uses "?bundleId=", so I'm not getting the update alert.

Hope it helps!

**Comment by ArtSabintsev** [comment] 2018-12-11 01:49
How recently did you update the app? The issue lasts for about 24 hours after launch.

**Comment by Bernica** [comment] 2018-12-11 11:16
Hi Arthur. The new version is ready for sale since december 6, thus, it's been 4+ days now. The _bundleId_ endpoint still returns the previous version tough.

**Comment by ArtSabintsev** [comment] 2018-12-11 12:33
Could you provide me with the bundleID and the current version of your app?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Bernica** [comment] 2018-12-11 17:52
Sure:
- https://itunes.apple.com/lookup?bundleId=com.vibelyst.Dapper
- https://itunes.apple.com/lookup?id=1381468910

It now responds with the updated data, took 5 days to do so. I'm about to release a new version, I can let you know when I do that if you want, so you can check the endpoints answers by yourself.

**Comment by ArtSabintsev** [comment] 2018-12-11 21:05
Thanks! Please do follow up here.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment] 2018-12-12 01:42
I'm going to close this issue since it's not a bug, but I will follow up on the conversation in here when you post back.

**Closed by ArtSabintsev** 2018-12-12 01:42 UTC

**Comment by ArtSabintsev** [comment] 2018-12-12 22:30
Ok I’ll take a look tonight

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment] 2018-12-13 03:59
Both seem to be returning `2.0.7` when I checked just now.
