### ISSUE TITLE
Version check comparison error. 

### ISSUE THREAD

**Issue by pavankataria** [ArtSabintsev/Siren#70] opened 2016-06-16 01:54 UTC
This issue simply shouldn't be happening. 

There needs to be another way to compare version numbers, 16.0 is certainly the same as 16 and shouldn't be treated as requiring a new version! :O I was shocked when I saw this..
Did some debugging and found the problem area... 
Today our app was accepted only for siren to cause our users to go into a never ending loop of installs..

![screen shot 2016-06-16 at 02 50 53](https://cloud.githubusercontent.com/assets/1791244/16103046/eaf295a0-336c-11e6-86c5-647d8fc77c79.png)

**Comment by ArtSabintsev** [comment] 2016-06-16 01:56
Even after merging this PR?

https://github.com/ArtSabintsev/Siren/commit/c0e40271d3e4b3f00a3084d672704a67f1d5c84c

**Comment by ArtSabintsev** [comment] 2016-06-16 02:01
Also, sometimes this happens IF the user is trying to download the app the moment it the servers update.  Unfortunately, the server metadata update is faster than the app being propagated to the CDNs.

**Comment by pavankataria** [comment] 2016-06-16 02:03
Yeah even after merging that PR... that PR I sent resolves another issue... 
Why is this comparison check being done btw if there is a comparison check already being done in another place?

**Comment by pavankataria** [comment] 2016-06-16 02:05
> Also, sometimes this happens IF the user is trying to download the app the moment it the servers update. Unfortunately, the server metadata update is faster than the app being propagated to the CDNs.
Actually, the meta data was all up to date, I checked the results object Siren grabs, and it was in a loop because of the problem code I provided above. This happens because of the decimal 0, mathematically, they're the same number, and therefor this comparison check should return false, but instead it's returning true..

**Comment by pavankataria** [comment] 2016-06-16 02:07
Ok I notice one comparison is being done to determine the type of upgrade alert that should be shown, while the first filter acts as a way to determine if a new update is required at all based on the ascending check... hmm, this as you can see errors out in this edge case.

**Comment by pavankataria** [comment] 2016-06-16 02:11
In regards to your suggestion that this might be related to a meta data sychronisation:
The version accepted into the app store was the new build submitted, version `16.0`. The app from the app store was then installed and Siren used the local version number of the bundle which was `16`.
This screenshot is for futher affirmation to demonstrate that this had nothing to do with synchronisation issues. 

![screen shot 2016-06-16 at 03 12 36](https://cloud.githubusercontent.com/assets/1791244/16103363/c1b04860-336f-11e6-8ee8-8644d1a7c40e.png)

**Comment by ArtSabintsev** [comment] 2016-06-16 02:24
Thanks for checking that out. 

I'm a bit exhausted right now, so I can't fully process why/what is going on. I'll take a look tomorrow.

**Comment by pavankataria** [comment] 2016-06-16 23:23
Hey, I hope you had a well rested night last night.  

Here's the damage that was caused last night, had people posting negative reviews right away at which point we had to take Siren out, and release another version straight after back into itunes connect... hoping apple would accept right away, but the damage was already done.
At least these guys care huh. lol

How's it going now anyway @ArtSabintsev ?

![](https://files.slack.com/files-pri/T03NKK94Q-F1HL7KZT5/screen_shot_2016-06-16_at_2.37.59_pm.png)

**Comment by ArtSabintsev** [comment] 2016-06-17 02:50
Ask for an expedited review without Siren installed, or up the version to 17.

Siren's only really tested to go from similar versioning systems:

16 -> 17
16.0 -> 16.1
16.0.0. -> 16.0.1 

I never tested it to go from 16 -> 16.0

Is that what you ended up doing? Going from 16 -> 16.0?

**Comment by ArtSabintsev** [comment] 2016-06-18 06:12
I am closing this issue for now, but we can continue the discussion in here at your convenience.

**Closed by ArtSabintsev** 2016-06-18 06:12 UTC

**Comment by pavankataria** [comment] 2016-06-19 16:23
Is there a reason you're closing this issue considering this issue hasn't been resolved? I think others should be made aware that this issue exists as they are most likely to implement this package for a production environment. Do you agree hiding the issue from the dashboard - which closing an issue does as though it's been resolved - will not help?

**Comment by pavankataria** [comment] 2016-06-19 16:25
That's weird, I thought I posted a response to your previous message, 

Here it is again, No. I didn't go from version `16` to `16.0`, apple's itunes connect will not allow you to do that. I went from version `15.0.1` to version `16` which is a similar versioning system.

**Comment by ArtSabintsev** [comment] 2016-06-20 02:53
Wait, you went from 15.0.1 -> 16, not 16.0.0?

**Comment by ArtSabintsev** [comment] 2016-06-20 03:24
As a follow-up, I am simply trying to understand your problem. In the 4 years that Harpy and Siren have been around, I have never had an issue like this come out. So, no, I don't believe this issue needs to be visible, as it's a one-off case, and the problem is not apparent to me.

Now, just so we're crystal clear, is the problem that you went from an `x.y.z` to an `x` versioning system? If so, what warranted that decision?

Also, I wrote a few tests this weekend, and my test shows that Siren handles that use case without issue.

https://github.com/ArtSabintsev/Siren/blob/master/Sample%20App/SirenTests/SirenTests.swift#L79-L82

**Comment by ArtSabintsev** [comment] 2016-06-20 03:25
@getaaron Can you chime in here as well (in case I'm missing something)? Thanks!

**Comment by pavankataria** [comment] 2016-06-20 09:24
No problem. Thanks, I'll just stick to the same versioning system :)

**Comment by ArtSabintsev** [comment] 2016-06-20 14:41
Thanks for following up!

Good luck, and if you continue using it, feel free to post issues and PRs!

Have a great week!
