### ISSUE TITLE
Screen turns black after calling wail()

### ISSUE THREAD

**Issue by redryerye** [ArtSabintsev/Siren#335] opened 2020-06-03 04:09 UTC
## Overview
Screen turns into a black screen right after wail() is called, and will no longer be able to do anything on the app.
Found out that screen turns black when `determineIfAlertPresentationRulesAreSatisfied()` is called in `validate()`. All looks fine until then.

## Environment
Xcode 11.2.1
Issue occurred both on Simulator and actual device. 

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**: Yes
- **What is your app's Bundle ID?**: 
- **When was the latest version of your app published to the App Store?**: Few days ago
- **Is your app published in the US App Store? If not, what App Store is it published in?**: Yes
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: Yes

**Comment by ArtSabintsev** [comment] 2020-06-03 04:20
Do you see the same issue in the sample app shipped with this repo?

**Comment by redryerye** [comment] 2020-06-03 04:23
@ArtSabintsev No it works fine in the sample app

**Comment by ArtSabintsev** [comment] 2020-06-03 05:03
Then the issue is something in how your app's launch sequence. For that, I cannot really help without you building a sample app replicating the issue. Closing the issue until you do that (if you choose to do that).

**Closed by ArtSabintsev** 2020-06-03 05:03 UTC
Labels: Potential Bug, Question

**Comment by dharmeshpatoliya** [comment] 2020-06-12 11:21
The same issue, Screen turns black even if commented your all app delegates methods in sample app.

**Comment by ArtSabintsev** [comment] 2020-06-12 14:11
Please open a new issue and follow the issue template there, as I require more info. Thank you!
