### ISSUE TITLE
App asking if should update even though version is newer than one on app store

### ISSUE THREAD

**Issue by royherma** [ArtSabintsev/Siren#111] opened 2016-12-18 16:11 UTC
App (test version) is v2.4, set in info.plist and is labeled in the "about" section as you can see in screenshot. However, Siren asking user if "should update" to v2.31 (live on app store).

Any ideas?

![image](https://cloud.githubusercontent.com/assets/3466248/21294759/59dc6faa-c54d-11e6-9b7d-2b8c532ae71f.png)

**Comment by royherma** [comment] 2016-12-18 16:13
Ok, seems to be related to the amount of trailing numbers in version - 2.31 > 2.4 but 2.31 < 2.40 ... adjusting to 2.40 for new version, although this does not seem to be intended behavior to me?

**Comment by ArtSabintsev** [comment] 2016-12-18 22:33
Hey, it is intended behavior.

We have X.Y.Z, where a check is performed at each digit. 

If Y = 4 in one version, and Y = 31 in another version, then 31 > 4, which is why you're seeing the behavior that you're seeing.

Closing this issue as this is intended behavior. Feel free to comment, and I will respond.

**Closed by ArtSabintsev** 2016-12-18 22:33 UTC
