### ISSUE TITLE
Cannot click screen after dismissing Siren Alert

### ISSUE THREAD

**Issue by mmdock** [ArtSabintsev/Siren#308] opened 2019-09-18 17:46 UTC
# If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?Yes.  5.2.1
- **What is your app's Bundle ID?**: 
com.dattch.dattch
- **When was the latest version of your app published to the App Store?**: 
Sep 16th.
- **Is your app published in the US App Store? If not, what App Store is it published in?**:
Yes
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: Haven't tested with the example app.

---

So, the flickering alert issue got resolved with this update, but now if I press "Next Time" or skip version in the `.option` and `.skip` alert types, the user cannot press on anything on the screen after they do so until after another app relaunch.

**Comment by ArtSabintsev** [comment] 2019-09-18 20:14
I've seen this in the simulator, but could not reproduce it on an iOS device. Can Is this happening on a device for you?

**Comment by mmdock** [comment] 2019-09-18 21:51
@ArtSabintsev yes, this is on physical device for me.  Device was iOS 13.1 beta 3 iPhone XS if that matters.  I didn't have a device on an earlier version to test on

**Comment by ArtSabintsev** [comment] 2019-09-20 02:46
Alright, I've been testing this using iOS 13.1 beta on my personal device and have not been able to get this issue to pop up at all. 

Can you try replicating this with the example app loaded onto your device using your bundleID?

**Comment by mmdock** [comment] 2019-09-24 16:52
@ArtSabintsev Haven't had a chance, been in a mad rush with all the other iOS 13 changes.  Should be able to look at it later today.

**Comment by mmdock** [comment] 2019-09-24 16:52
Whoops, didn't mean to close

**Comment by ArtSabintsev** [comment] 2019-09-25 01:34
all good - thanks for following up!

**Comment by ArtSabintsev** [comment] 2019-09-26 15:19
Alright, going to close this issue as I tested this in a personal production app that just had an update and did not see any issue on 13.1. Feel free to reopen the issue if it persists on your end. 

A video example would be awesome, if possible.

**Closed by ArtSabintsev** 2019-09-26 15:19 UTC
Labels: Bug, Question

**Comment by sumeet-gupta** [comment] 2019-10-01 08:59
Still happening for me, tested it on iOS 13.1.1.

**Comment by ArtSabintsev** [comment] 2019-10-01 11:40
Please provide me with a sample app that replicates this behavior on a device, as I am unable to replicate it on my end

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
