### ISSUE TITLE
Blocking UI when the alert is dismissed (again)

### ISSUE THREAD

**Issue by MarkChrisLevy** [ArtSabintsev/Siren#322] opened 2020-01-07 20:21 UTC
Hi,
I'm using latest Siren from 5.1 branch and it seems that error reported in #313 is back - after hidding Siren's alert, the other window in the app is not getting focus/touch so basically app is blocked. After reading comments from the metioned issue there only way to solve the issue was adding in cleanUp function the following:
```
        for window in UIApplication.shared.windows {
            if (window.rootViewController != nil && window.rootViewController! is SirenViewController) {
              window.rootViewController = nil
              window.resignKey()
              window.removeFromSuperview()
            }
        }

```

**Comment by ArtSabintsev** [comment] 2020-01-09 03:08
Hey Mark,

Is this happening in the sample app as well? Can you faithfully reproduce it?

**Comment by MarkChrisLevy** [comment] 2020-01-09 10:22
@ArtSabintsev It happens all the time in my app, I didn't test it in the sample app but I will. If I will not be able to reproduce it in the sample app I will create my sample app, with the environment that I'm using (@ionic/capacitor).

**Comment by ArtSabintsev** [comment] 2020-01-14 22:17
hey, just following up on your progress. Thanks!

**Comment by MarkChrisLevy** [comment] 2020-01-16 19:25
Hi @ArtSabintsev, please do following steps with example project:
- edit Main storyboard and in the view controller add text input
- set Main interface to Main.storyboard
- run and dismiss with "next time"
- you should see that text input cannot be activated/focused

I'm running the project in ios 13 simulator.

**Comment by ArtSabintsev** [comment] 2020-01-19 20:04
Hey, I followed your directions, but cannot reproduce the bug. See the attached screen capture.


![ezgif-3-dc0647f72683](https://user-images.githubusercontent.com/854860/72687555-e81a5280-3acc-11ea-9f8d-cc2dbe42d4ad.gif)

**Comment by MarkChrisLevy** [comment] 2020-01-19 21:38
@ArtSabintsev You forgot to add text field / text input to the view controller, when text field is present after dismissing alert it cannot be focused:
![siren](https://user-images.githubusercontent.com/10324672/72688929-60eccf00-3b0c-11ea-8282-2247cec1bf54.gif)

In screen recording above you may see that cursor is above text field and it cannot be focused.

**Comment by ArtSabintsev** [comment] 2020-01-20 04:19
Tried it again. Still can't reproduce it. See below.

![ezgif-7-0119bdb1c808](https://user-images.githubusercontent.com/854860/72698433-2ab24e00-3b12-11ea-88c3-efd2a9469c3f.gif)

**Comment by MarkChrisLevy** [comment] 2020-01-21 16:24
@ArtSabintsev Weird...  Ok, I prepared demo app that is uses capacitor and siren:

- repo https://github.com/MarkChrisLevy/siren-capacitor-test
- after cloning, open dir and:
   - npm install
   - npx cap update ios
   - npx cap open ios
   - run simulator

All changes related to Siren are in ios/App/App/AppDelegate.swift and it behaves exactly as I wrote - after dismissing Siren, the web view window is not active. I'm not saying that this is an issue with Siren, but I cannot figure out what to change to make Siren dismissing properly (except changing cleanUp as described in https://github.com/ArtSabintsev/Siren/issues/322#issue-546487980).

Thanks.

**Comment by ArtSabintsev** [comment] 2020-01-23 03:15
Ah, you are using Ionic/Capacitor. 

To be transparent and honest, I am not in the business of supporting changes for the benefit of third-party tooling. Not because I don't want to, but because I don't have time to maintain those changes / verify them as time progresses and the library evolves. My goal has always been to solve for the majority, the 80%. 

I hope you understand my stance. You're more than welcome to fork this repo. As you can see by the updates, they happen once a year or so, and I have no future plans for massive rewrites of the library, at least not anytime soon. This will allow you to easily maintain your fork against this master branch.

I hope you understand my stance.  

I am closing the issue, and will lock it in the future, after I've heard back (if you choose to respond), or after enough time has passed without any further commentary.

Thank you for bringing this to my attention and my apology for not coming to the solution you desired.

**Closed by ArtSabintsev** 2020-01-23 03:15 UTC
Labels: Potential Bug

**Comment by MarkChrisLevy** [comment] 2020-01-25 20:58
@ArtSabintsev Sure, thanks for your time and for making Siren.
